image: dock0/arch

before_script:
  - pacman -Syy --noconfirm
  - pacman -Syu --noconfirm
  - pacman -S python --noconfirm
  - pacman -S python-pip --noconfirm
  - pip install pytest
test:
  script:
    - python setup.py install
    - cd marcador
    - pytest


release:
  image: joajfreitas/arch-python
  stage: deploy
  only:
    - release

  script:
    - python setup.py sdist
    - pip install twine
    - twine upload -u joajfreitas -p $PYPI_PASSWORD dist/* 
