#!/bin/bash

run_rofi () {
	rofi -dmenu -p "> " "$@"
}

addBookmark () {
	URL=$(run_rofi -mesg "Insert an url.")
	if [[ $? -eq 1 ]]; then
		exit
	fi
	TAGS=$(run_rofi -mesg "Insert some comma separated tags.")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	bookmarks -a $URL, $TAGS $DB
}

openURL () {
	number=$1
	$BROWSER $(bookmarks -f ${number::-1} $DB)
}

listTags () {
	tag=$(bookmarks -l $DB | run_rofi -mesg "Enter to select tag.")
	if [[ $? -eq 1 ]] ; then
		exit
	fi
	url=$(bookmarks -t $tag $DB | run_rofi -mesg "Enter to select a bookmark")
	if [[ $? -eq 1 ]] ; then
		exit
	fi
	openURL $url
}

main () {


	selection=$(bookmarks -p $DB | awk 'NF == 2 { $0 = $0 "No tag" }; { $2 = substr($2,0,60); print $1"\t"$2"\t"$3}' | column -t | run_rofi -kb-custom-1 "${new_bookmark}" -kb-custom-2 "${list_tags}" -mesg "Enter to select a bookmark. Add a new one with Alt+n.
Or search for tags with Alt+t.")
	val=$?
	if [[ $val -eq 1 ]]; then
		exit
	elif [[ $val -eq 10 ]]; then
		addBookmark
	elif [[ $val -eq 11 ]]; then
		listTags
	else
		openURL $selection
	fi


}

if [ $# -eq 0 ] 
	then
    echo "Please provide a bookmarks file"
	exit
fi

DB=$1

#shortcuts
new_bookmark="Alt+n"
list_tags="Alt+t"

touch $DB &

main
