#!/usr/bin/env bash

TERM=xterm
EDITOR=vim

run_rofi () {
	rofi -lines 15 -width 800 -dmenu -p "> " "$@"
}

addBookmark () {
	URL=$(xsel | head -n1 | run_rofi -mesg "Insert an url.")
	if [[ $? -eq 1 ]]; then
		exit
	fi
	TAGS=$(run_rofi -mesg "Insert some comma separated tags.")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	bookmarks add $URL $TAGS $DB
}

openURL () {
	number=$1
	$BROWSER $(bookmarks find ${number::-1} $DB)
}

listTags () {
	tag=$(bookmarks list-tags $DB | run_rofi -mesg "Enter to select tag.")
	if [[ $? -eq 1 ]] ; then
		exit
	fi
	url=$(bookmarks tag-search $tag $DB | run_rofi -mesg "Enter to select a bookmark")
	if [[ $? -eq 1 ]] ; then
		exit
	fi
	openURL $url
}

delete () {
	number=$1
	bookmarks rm ${number::-1} $DB

	main
}

edit () {
	id=$(echo $1 | tr '.' '\n' | head -n1)
	bookmarks edit $id $DB
	main
	
}

main () {


	selection=$(bookmarks print $DB | awk 'NF == 2 { $0 = $0 "No tag" }; { $2 = substr($2,0,70); print $1"\t"$2"\t"$3}' | column -t | run_rofi -kb-custom-1 "${new_bookmark_shortcut}" -kb-custom-2 "${list_tags_shortcut}" -kb-custom-3 "${delete_shortcut}" -kb-custom-4 "${edit_shorcut}" -mesg "Enter to select a bookmark. Alt+n to create a new one.
Edit a bookmarks with Alt+a. Remove one with Alt+d. Search for tags with Alt+t.")
	val=$?
	if [[ $val -eq 1 ]]; then
		exit
	elif [[ $val -eq 10 ]]; then
		addBookmark
	elif [[ $val -eq 11 ]]; then
		listTags
	elif [[ $val -eq 12 ]]; then
		delete $selection
	elif [[ $val -eq 13 ]]; then
		edit $selection
	else
		openURL $selection
	fi
}

if [ $# -eq 0 ] 
	then
    echo "Please choose a bookmark file path."
	exit
fi

DB=$1

#shortcuts
new_bookmark_shortcut="Alt+n"
list_tags_shortcut="Alt+t"
delete_shortcut="Alt+d"
edit_shorcut="Alt+a"

touch $DB &

main
