#!/bin/bash

run_rofi () {
	rofi -lines 15 -width 800 -dmenu -p "> " "$@"
}

addBookmark () {
	URL=$(run_rofi -mesg "Insert an url.")
	if [[ $? -eq 1 ]]; then
		exit
	fi
	TAGS=$(run_rofi -mesg "Insert some comma separated tags.")
	if [[ $? -eq 1 ]]; then
		exit
	fi

	bookmarks -a $URL, $TAGS $DB
}

openURL () {
	number=$1
	$BROWSER $(bookmarks -f ${number::-1} $DB)
}

listTags () {
	tag=$(bookmarks -l $DB | run_rofi -mesg "Enter to select tag.")
	if [[ $? -eq 1 ]] ; then
		exit
	fi
	url=$(bookmarks -t $tag $DB | run_rofi -mesg "Enter to select a bookmark")
	if [[ $? -eq 1 ]] ; then
		exit
	fi
	openURL $url
}

delete () {
	number=$1
	bookmarks -rf ${number::-1} $DB

	main
}

edit () {
	bookmark=$@
	current_date=$(date +'%s')
	echo $bookmark > /tmp/bookmarks-$current_date
	$TERM -e "'$EDITOR' /tmp/bookmarks-$current_date" & export pid=$!
	kill -0 $pid
	status=$?
	while [ $status -eq 0 ]
	do
		kill -0 $pid > /dev/null 2>&1
		status=$?
		sleep 0.1
	done
	new_bookmark=$(</tmp/bookmarks-$current_date)

	bookmarks -rf $(echo $bookmark | tr '.' '\n' | head -n1) $DB

	url=$(echo $new_bookmark | tr ' ' '\n' | head -2 | tail -1) 
	tags=$(echo $new_bookmark | tr ' ' '\n' | head -3 | tail -1) 
	bookmarks -a $url, $tags $DB

	main
	
}

main () {


	selection=$(bookmarks -p $DB | awk 'NF == 2 { $0 = $0 "No tag" }; { $2 = substr($2,0,70); print $1"\t"$2"\t"$3}' | column -t | run_rofi -kb-custom-1 "${new_bookmark_shortcut}" -kb-custom-2 "${list_tags_shortcut}" -kb-custom-3 "${delete_shorcut}" -kb-custom-4 "${edit_shorcut}" -mesg "Enter to select a bookmark. Alt+n to create a new one.
Edit a bookmarks with Alt+a. Remove one with Alt+d. Search for tags with Alt+t.")
	val=$?
	if [[ $val -eq 1 ]]; then
		exit
	elif [[ $val -eq 10 ]]; then
		addBookmark
	elif [[ $val -eq 11 ]]; then
		listTags
	elif [[ $val -eq 12 ]]; then
		delete $selection
	elif [[ $val -eq 13 ]]; then
		edit $selection
	else
		openURL $selection
	fi
}

if [ $# -eq 0 ] 
	then
    echo "Please choose a bookmarks file path."
	exit
fi

DB=$1

#shortcuts
new_bookmark_shorcut="Alt+n"
list_tags_shortcut="Alt+t"
delete_shortcut="Alt+d"
edit_shorcut="Alt+a"

touch $DB &

main
