name: Marcador CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Version
      run: rustc --version
    - name: Build
      run: cargo rustc --lib --verbose -- -D warnings
       | cargo rustc --bin main --verbose -- -D warnings

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings

  format-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run rustfmt
          run: cargo fmt
